stages:
  - tests
  - wheels


.tests: &tests
  stage: tests
  script:
    - pip install -e .[all]
    - pytest

#tests_python_36:
#  <<: *tests
#  image: diefans/python3.6-alpine-cython:0.1.0

tests_python_37:
  <<: *tests
  image: diefans/python3.7-alpine-cython:0.1.0

# failing: https://github.com/Tinche/cattrs/issues/46
tests_python_38:
  <<: *tests
  image: diefans/python3.8-alpine-cython:0.1.0

tests_python_39:
  <<: *tests
  image: diefans/python3.9-alpine-cython:0.2.0


.wheels: &wheels
  stage: wheels
  image: quay.io/pypa/manylinux2014_x86_64
  script:
    #- mkdir ./dist
    - ./build_manylinux.sh
    #- cp ./wheelhouse/buvar* ./dist
  artifacts:
    when: on_success
    paths:
      - dist
    expire_in: 30 mins

wheels_python39_x86_64:
  <<: *wheels
  variables:
    PLATFORM: manylinux2014_x86_64
    PYTHON_VERSIONS: cp39-cp39

wheels_python38_x86_64:
  <<: *wheels
  variables:
    PLATFORM: manylinux2014_x86_64
    PYTHON_VERSIONS: cp38-cp38

wheels_python37_x86_64:
  <<: *wheels
  variables:
    PLATFORM: manylinux2014_x86_64
    PYTHON_VERSIONS: cp37-cp37m

#wheels_python36_x86_64:
#  <<: *wheels
#  variables:
#    PLAT: manylinux2010_x86_64
#    PYTHON_VERSIONS: cp36-cp36m
