stages:
  - tests
  - wheels


.tests: &tests
  stage: tests
  script:
    - pip install cython .[all,tests]
    - pytest

tests_python_36:
  <<: *tests
  image: python:3.6-alpine

tests_python_37:
  <<: *tests
  image: python:3.7-alpine


.wheels: &wheels
  stage: wheels
  image: quay.io/pypa/manylinux2010_x86_64
  script:
    - ./build_manylinux.sh
  artifacts:
    when: on_success
    paths:
      - wheelhouse
    expire_in: 30 mins

wheels_python37_x86_64:
  <<: *wheels
  variables:
    PLAT: manylinux2010_x86_64
    PYTHON_VERSIONS: cp37-cp37m

wheels_python36_x86_64:
  <<: *wheels
  variables:
    PLAT: manylinux2010_x86_64
    PYTHON_VERSIONS: cp36-cp36m
