version: '3'

volumes:
  wheelhouse: {}
  pipcache: {}
  build: {}


services:
  manylinux2010:
    image: quay.io/pypa/manylinux2010_x86_64:latest
    user: root
    environment:
      PLAT: manylinux2010_x86_64
    volumes:
      - "./:/io"
      #- "wheelhouse:/io/wheelhouse"
      - "pipcache:/root/.cache/pip"
      #- "build:/io/build"
    tmpfs:
      - /io/build
      - /io/tests/__pycache__
      - /io/wheels
      - /io/wheelhouse
    working_dir: /io
    command: ./build_manylinux.sh
