name: "Build and Tests"

on:
  push:
    branches:
      - "*"
    # tag is already build in branch
    tags-ignore:
      - "*"
  pull_request:
    branches: ["master"]

jobs:
  pytest:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    strategy:
      fail-fast: false
      matrix:
        version: ["3.12", "3.11", "3.10"]

    name: Testing ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.version }}"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[tests]"

      - name: Run tests
        run: |
          pytest
