name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Wait for build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh run watch --exit-status "$(gh run list -w build.yaml -b master -L 1 --json databaseId,headSha -q '.[]|[.databaseId, .headSha]|@tsv' | grep ${{ github.sha }} | cut -f1)"

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          debug: true
